// Shared app foundation: the single mutable `state` object, the DOM element
// map `els`, and the status-line helper every feature module reports through.
// This module is the bottom of the app's import graph — it must never import
// a feature module (only pure/leaf modules like tuning.mjs and eta.mjs), so
// any feature module can import it without creating an eval-time cycle.

import { createRideEstimator } from "../ride/eta.mjs";
import {
  DEFAULT_BEACON_COLOR,
  DEFAULT_BEACON_DIAMETER_METERS,
  DEFAULT_BEACON_ENABLED,
  DEFAULT_BEACON_HEIGHT_METERS,
  DEFAULT_BEACON_OPACITY,
  DEFAULT_CAMERA_ANGLE_DEGREES,
  DEFAULT_CAMERA_BEHIND_METERS,
  DEFAULT_CAMERA_DEBUG_ENABLED,
  DEFAULT_CAMERA_ZOOM,
  DEFAULT_CLIMB_FOCUS_MODE,
  DEFAULT_CLIMB_ORBIT_SECONDS_PER_REV,
  DEFAULT_DURATION_FORMAT,
  DEFAULT_FIRST_PERSON_CAMERA_HEIGHT_METERS,
  DEFAULT_GHOST_RIDER_ENABLED,
  DEFAULT_GRADE_INTERVAL_SECONDS,
  DEFAULT_HUD_DOCK_COLLAPSED,
  DEFAULT_HUD_FIELD_ORDER,
  DEFAULT_HUD_VISIBLE_COUNT,
  DEFAULT_MAP_LABELS_ENABLED,
  DEFAULT_MAP_RENDERER,
  DEFAULT_MAX_HEART_RATE_BPM,
  DEFAULT_OVERVIEW_MODE,
  DEFAULT_RESTING_HEART_RATE_BPM,
  DEFAULT_RIDER_VISIBILITY_ENABLED,
  DEFAULT_ROUTE_GRADE_COLORS_ENABLED,
  RIDE_REPLAY_DEFAULT_SPEED,
  DEFAULT_SCREENSHOT_ASPECT,
  DEFAULT_SCREENSHOT_WIDTH,
  DEFAULT_SHOW_MINIMAP,
  DEFAULT_SHOW_SCREENSHOT_BUTTON,
  DEFAULT_STREET_IMAGERY_ENABLED,
  DEFAULT_TERRAIN_AVOID_ENABLED,
  DEFAULT_TERRAIN_CLEARANCE_METERS,
  DEFAULT_TERRAIN_TILES_ENABLED,
  DEFAULT_THEATER_HIDE_CLIMB_BANNER,
  DEFAULT_THEATER_HIDE_CLOCK,
  DEFAULT_THEATER_HIDE_CONTROLS,
  DEFAULT_THEATER_HIDE_DEMO_CHIP,
  DEFAULT_THEATER_HIDE_DOCK,
  DEFAULT_THEATER_HIDE_METERS,
  DEFAULT_THEATER_HIDE_MINIMAP,
  DEFAULT_THEATER_HIDE_ROUTE_AHEAD,
  DEFAULT_TIME_FORMAT,
} from "./tuning.mjs";

export const state = {
  route: [],
  // Display name shown above the route classification: a gallery ride's
  // curated title, else the GPX's own <name>, else the uploaded filename.
  routeName: null,
  // Source metadata for a library route. Gallery export keeps this content
  // intact and replaces only its preview camera with the live map camera.
  galleryMetadata: null,
  // Detected climbs for the loaded route (see climbs.mjs), recomputed once
  // per route load in updateRouteOverview and read every ride tick to drive
  // the live "current climb" / "next climb" status.
  climbs: [],
  progressMeters: 0,
  simulating: false,
  pedaling: false,
  movementLoopActive: false,
  tickRaf: null,
  tickTimeout: null,
  lastTick: 0,
  routeLines: [],
  // The recording view's ridden-only route line (map/route-trail.mjs): its
  // segments, their polylines and the progress it was last cut at.
  routeTrail: null,
  riderDot: null,
  riderBeacon: null,
  map: null,
  // Which engine draws the 3D map: "google3d" (photorealistic tiles) or
  // "virtual" (the synthetic world in world/). `maps3d` is that engine's
  // library — Google's maps3d or its virtual stand-in, same API either way.
  mapProvider: null,
  maps3d: null,
  // The user's renderer choice (persisted): "google" | "virtual".
  mapRenderer: DEFAULT_MAP_RENDERER,
  minimapMap: null,
  minimapPaths: [],
  minimapMarker: null,
  trainerSpeedKph: null,
  trainerPowerWatts: null,
  trainerCadenceRpm: null,
  trainerCaloriesKcal: null,
  powerCaloriesKcal: 0,
  trainerHeartRateBpm: null,
  strapHeartRateBpm: null,
  heartRateStatusText: null,
  heartRateRefreshTimer: null,
  demoModeActive: false,
  demoModel: null,
  demoHistorySamples: [],
  demoTimerSeconds: 0,
  demoCaloriesKcal: 0,
  gradeUpdateIntervalSeconds: DEFAULT_GRADE_INTERVAL_SECONDS,
  lastSlowUiAt: 0,
  lastRiderDot: null,
  lastRiderBeacon: null,
  lastRideSavedAt: 0,
  lastGalleryMetadataRefreshMs: 0,
  profileHoverMeters: null,
  profileSelectStartMeters: null,
  profileSelectStartX: null,
  profileSelectPointerId: null,
  profileSelecting: false,
  profileSelectionSuppressClick: false,
  selectedProfileSegment: null,
  userInteracting: false,
  interactionSettleTimer: null,
  interactionDotLoopActive: false,
  // "overview" while a freshly loaded route is framed whole, "manual" after
  // the user grabs the overview camera, "follow" once movement starts.
  cameraMode: "follow",
  overviewCamera: null,
  overviewRoute: null,
  activeOverviewMode: DEFAULT_OVERVIEW_MODE,
  // How the whole-route overview is presented (user setting): "static" |
  // "orbit" | "flyby" | "flyover" | "satellite" | "satellite-north".
  // overviewAnim holds the live animation state for the animated modes (orbit /
  // flyby / flyover); its loop drives the map directly.
  overviewActive: false,
  overviewMenuOpen: false,
  climbOverviewMenuOpen: false,
  cameraViewMenuOpen: false,
  cameraViewPreset: null,
  overviewMode: DEFAULT_OVERVIEW_MODE,
  climbFocusMode: DEFAULT_CLIMB_FOCUS_MODE,
  climbOrbitSecondsPerRev: DEFAULT_CLIMB_ORBIT_SECONDS_PER_REV,
  focusedClimbIndex: null,
  overviewAnim: null,
  overviewAnimLoopActive: false,
  cameraFlight: null,
  cameraFlightLoopActive: false,
  // Live overview ↔ chase transition-arc flight ({ arc, startMs, onComplete },
  // see camera/transition-camera.mjs); its loop owns the map camera while set.
  cameraTransition: null,
  cameraTransitionLoopActive: false,
  cameraZoom: DEFAULT_CAMERA_ZOOM,
  cameraAngleDegrees: DEFAULT_CAMERA_ANGLE_DEGREES,
  cameraBehindMeters: DEFAULT_CAMERA_BEHIND_METERS,
  cameraHeadingOffsetDegrees: 0,
  cameraOffsetForwardMeters: 0,
  cameraOffsetRightMeters: 0,
  cameraCenterAltitudeOffsetMeters: 0,
  firstPersonCameraHeightMeters: DEFAULT_FIRST_PERSON_CAMERA_HEIGHT_METERS,
  centerRider: true,
  screenshotInProgress: false,
  showScreenshotButton: DEFAULT_SHOW_SCREENSHOT_BUTTON,
  screenshotAspect: DEFAULT_SCREENSHOT_ASPECT,
  screenshotWidth: DEFAULT_SCREENSHOT_WIDTH,
  beaconEnabled: DEFAULT_BEACON_ENABLED,
  beaconDiameterMeters: DEFAULT_BEACON_DIAMETER_METERS,
  beaconHeightMeters: DEFAULT_BEACON_HEIGHT_METERS,
  beaconOpacity: DEFAULT_BEACON_OPACITY,
  beaconColor: DEFAULT_BEACON_COLOR,
  terrainAvoidEnabled: DEFAULT_TERRAIN_AVOID_ENABLED,
  terrainClearanceMeters: DEFAULT_TERRAIN_CLEARANCE_METERS,
  // Augment the route-based terrain estimate with real ground elevation from
  // online Mapzen Terrarium tiles (map/terrain-tiles.mjs).
  terrainTilesEnabled: DEFAULT_TERRAIN_TILES_ENABLED,
  routeGradeColorsEnabled: DEFAULT_ROUTE_GRADE_COLORS_ENABLED,
  cameraLiftMeters: 0,
  cameraLiftTargetMeters: 0,
  lastLiftComputeMs: 0,
  lastLiftSmoothMs: 0,
  // Follow-camera rider-visibility swing (see follow-camera.mjs): how far the
  // camera is currently swung sideways around the rider to see past a hill,
  // its eased target, and the last compute/smooth timestamps. Runtime only.
  riderVisibilityNudgeEnabled: DEFAULT_RIDER_VISIBILITY_ENABLED,
  cameraVisNudgeDegrees: 0,
  cameraVisNudgeTargetDegrees: 0,
  lastVisNudgeComputeMs: 0,
  lastVisNudgeSmoothMs: 0,
  mapFullscreen: false,
  theaterMode: false,
  finishOrbitActive: false,
  theaterHideClock: DEFAULT_THEATER_HIDE_CLOCK,
  theaterHideMeters: DEFAULT_THEATER_HIDE_METERS,
  theaterHideDock: DEFAULT_THEATER_HIDE_DOCK,
  theaterHideClimbBanner: DEFAULT_THEATER_HIDE_CLIMB_BANNER,
  theaterHideDemoChip: DEFAULT_THEATER_HIDE_DEMO_CHIP,
  theaterHideControls: DEFAULT_THEATER_HIDE_CONTROLS,
  theaterHideMinimap: DEFAULT_THEATER_HIDE_MINIMAP,
  theaterHideRouteAhead: DEFAULT_THEATER_HIDE_ROUTE_AHEAD,
  distanceUnits: "metric",
  energyUnits: "kcal",
  timeFormat: DEFAULT_TIME_FORMAT,
  durationFormat: DEFAULT_DURATION_FORMAT,
  restingHeartRateBpm: DEFAULT_RESTING_HEART_RATE_BPM,
  maxHeartRateBpm: DEFAULT_MAX_HEART_RATE_BPM,
  ftpWatts: null,
  draggedHudField: null,
  fullscreenClockTimer: null,
  showMinimap: DEFAULT_SHOW_MINIMAP,
  mapLabelsEnabled: DEFAULT_MAP_LABELS_ENABLED,
  // Street-level imagery (street-view/): the persisted switch, the user's own
  // Mapillary client token (empty = use the deployed default) and username
  // (prefers their own uploads), plus the feature's live runtime state in one
  // object — the frame index for the loaded route (indexRoute is the route it
  // was built for, so a route swap is detected by identity), the in-flight
  // scan, the playback plan built from the index (planKey identifies the
  // cached one; planFinal = built from the complete scan), the asset store
  // and its database, the mounted renderer, and a status for the chip
  // ("off" | "no-token" | "scanning" | "ready" | "token-error" | "load-error").
  streetImageryEnabled: DEFAULT_STREET_IMAGERY_ENABLED,
  mapillaryToken: "",
  mapillaryUsername: "",
  streetImagery: {
    token: null,
    index: null,
    indexRoute: null,
    scanController: null,
    scanPromise: null,
    scanDone: false,
    scan: { done: 0, total: 0 },
    coverage: null,
    source: null,
    dbPromise: null,
    storePromise: null,
    store: null,
    plan: null,
    planKey: null,
    planPromise: null,
    planController: null,
    planFinal: false,
    planBuiltAt: -Infinity,
    planIndexSize: 0,
    renderer: null,
    rendererPromise: null,
    rendererRetryAt: 0,
    visible: false,
    status: "off",
    loopTimer: null,
    // coverTimer delays hiding the 3D map until the layer's fade-in is done.
    coverTimer: null,
  },
  // Ride replay (replay/): the recorded ride behind the loaded route, if the
  // route came from a timestamped GPX or a FIT file. `timeline` is the
  // ride-timeline.mjs model (null for a plain planned route), `elapsedSeconds`
  // the playhead in ride time, `playing` makes the replay the movement source
  // (see movement.mjs#isMoving), `speed` the playback multiplier. The video
  // export keeps its capture controller in `recorder` while a recording runs,
  // `statusTimer` refreshes the REC chip's progress, and `outroTimer` is the
  // finish-orbit tail before the file is saved.
  replay: {
    timeline: null,
    sourceName: null,
    stravaActivityId: null,
    pendingStravaActivityId: null,
    playing: false,
    elapsedSeconds: 0,
    speed: RIDE_REPLAY_DEFAULT_SPEED,
    lastTelemetryIndex: -1,
    recorder: null,
    recording: false,
    exportStarting: false,
    statusTimer: null,
    outroTimer: null,
    // Set while the recording waits for the camera to arrive at the rider
    // before starting the replay (replay-mode.mjs#startReplayWhenCameraArrives).
    cameraWait: null,
  },
  // Ghost rider (replay/ghost-ui.mjs): racing the loaded recording while the
  // rider moves under their own power. `enabled` is the persisted switch in
  // the Ride replay card; the race itself is `active` from the first
  // own-power tick until a reset / replay playback, `startElapsedSeconds` the
  // moment in the recording where it joined and `raceSeconds` the rider's
  // moving time since (both saved with the ride, see ghost-race.mjs). The
  // rest is the ghost's live 3D beacon, minimap marker and last drawn spot.
  ghostRiderEnabled: DEFAULT_GHOST_RIDER_ENABLED,
  ghost: {
    active: false,
    startElapsedSeconds: 0,
    raceSeconds: 0,
    beacon: null,
    minimapMarker: null,
    lastBeaconPoint: null,
  },
  cameraDebugEnabled: DEFAULT_CAMERA_DEBUG_ENABLED,
  cameraDebugCollapsed: false,
  cameraDebugTimer: null,
  overviewDebugLine: null,
  overviewDebugLineMode: null,
  overviewDebugLineSource: null,
  hudFieldOrder: [...DEFAULT_HUD_FIELD_ORDER],
  hudVisibleCount: DEFAULT_HUD_VISIBLE_COUNT,
  hudDockCollapsed: DEFAULT_HUD_DOCK_COLLAPSED,
  profileSeries: { speed: true, power: true, heartRate: true },
  // startDistance of the climb whose mini-profile is currently drawn in the
  // banner, so it is only rebuilt when the upcoming climb changes.
  bannerClimbKey: null,
  // Per-session pace tracker feeding the smart ETA; reset on new GPX load.
  rideEstimator: createRideEstimator(),
};

export const els = {
  brandName: document.querySelector("#brandName"),
  settingsBtn: document.querySelector("#settingsBtn"),
  mapSettingsShortcutBtn: document.querySelector("#mapSettingsShortcutBtn, #fullscreenSettingsBtn"),
  settingsDialog: document.querySelector("#settingsDialog"),
  settingsCloseBtn: document.querySelector("#settingsCloseBtn"),
  settingsDoneBtn: document.querySelector("#settingsDoneBtn"),
  settingsTabs: document.querySelectorAll("#settingsDialog [data-settings-tab]"),
  settingsPanels: document.querySelectorAll("#settingsDialog [data-settings-panel]"),
  settingsPanelTitle: document.querySelector("#settingsPanelTitle"),
  settingsPanelSubtitle: document.querySelector("#settingsPanelSubtitle"),
  apiKeySection: document.querySelector("#apiKeySection"),
  mapsApiKeyInput: document.querySelector("#mapsApiKeyInput"),
  mapsApiKeySaveBtn: document.querySelector("#mapsApiKeySaveBtn"),
  gpxFile: document.querySelector("#gpxFile"),
  gpxChip: document.querySelector("#gpxChip"),
  gpxChipName: document.querySelector("#gpxChipName"),
  difficultyStat: document.querySelector("#difficultyStat"),
  difficultyDetail: document.querySelector("#difficultyDetail"),
  galleryDialog: document.querySelector("#galleryDialog"),
  climbsSection: document.querySelector("#climbsSection"),
  climbStatus: document.querySelector("#climbStatus"),
  climbStatusHeadline: document.querySelector("#climbStatusHeadline"),
  climbStatusDetail: document.querySelector("#climbStatusDetail"),
  climbsList: document.querySelector("#climbsList"),
  distanceStat: document.querySelector("#distanceStat"),
  riddenStat: document.querySelector("#riddenStat"),
  remainingStat: document.querySelector("#remainingStat"),
  etaStat: document.querySelector("#etaStat"),
  ascentStat: document.querySelector("#ascentStat"),
  descentStat: document.querySelector("#descentStat"),
  ascentLeftStat: document.querySelector("#ascentLeftStat"),
  gradeStat: document.querySelector("#gradeStat"),
  altitudeStat: document.querySelector("#altitudeStat"),
  powerStat: document.querySelector("#powerStat"),
  speedStat: document.querySelector("#speedStat"),
  trainerStat: document.querySelector("#trainerStat"),
  heartRateStat: document.querySelector("#heartRateStat"),
  caloriesStat: document.querySelector("#caloriesStat"),
  speedInput: document.querySelector("#speedInput"),
  speedOutput: document.querySelector("#speedOutput"),
  gradeIntervalInput: document.querySelector("#gradeIntervalInput"),
  gradeIntervalOutput: document.querySelector("#gradeIntervalOutput"),
  distanceUnitSelect: document.querySelector("#distanceUnitSelect"),
  energyUnitSelect: document.querySelector("#energyUnitSelect"),
  timeFormatSelect: document.querySelector("#timeFormatSelect"),
  durationFormatSelect: document.querySelector("#durationFormatSelect"),
  overviewModeSelect: document.querySelector("#overviewModeSelect"),
  climbFocusModeSelect: document.querySelector("#climbFocusModeSelect"),
  climbOrbitSpeedInput: document.querySelector("#climbOrbitSpeedInput"),
  climbOrbitSpeedOutput: document.querySelector("#climbOrbitSpeedOutput"),
  cameraZoomInput: document.querySelector("#cameraZoomInput"),
  cameraZoomOutput: document.querySelector("#cameraZoomOutput"),
  cameraAngleInput: document.querySelector("#cameraAngleInput"),
  cameraAngleOutput: document.querySelector("#cameraAngleOutput"),
  cameraBehindInput: document.querySelector("#cameraBehindInput"),
  cameraBehindOutput: document.querySelector("#cameraBehindOutput"),
  firstPersonHeightInput: document.querySelector("#firstPersonHeightInput"),
  firstPersonHeightOutput: document.querySelector("#firstPersonHeightOutput"),
  cameraReadout: document.querySelector("#cameraReadout"),
  centerRiderInput: document.querySelector("#centerRiderInput"),
  resetCameraBtn: document.querySelector("#resetCameraBtn"),
  beaconEnabledInput: document.querySelector("#beaconEnabledInput"),
  beaconDiameterInput: document.querySelector("#beaconDiameterInput"),
  beaconDiameterOutput: document.querySelector("#beaconDiameterOutput"),
  beaconHeightInput: document.querySelector("#beaconHeightInput"),
  beaconHeightOutput: document.querySelector("#beaconHeightOutput"),
  beaconOpacityInput: document.querySelector("#beaconOpacityInput"),
  beaconOpacityOutput: document.querySelector("#beaconOpacityOutput"),
  beaconColorInput: document.querySelector("#beaconColorInput"),
  terrainAvoidInput: document.querySelector("#terrainAvoidInput"),
  terrainClearanceInput: document.querySelector("#terrainClearanceInput"),
  terrainClearanceOutput: document.querySelector("#terrainClearanceOutput"),
  terrainTilesInput: document.querySelector("#terrainTilesInput"),
  terrainAttribution: document.querySelector("#terrainAttribution"),
  worldAttribution: document.querySelector("#worldAttribution"),
  routeGradeColorsInput: document.querySelector("#routeGradeColorsInput"),
  mapRendererSelect: document.querySelector("#mapRendererSelect"),
  resetRenderingBtn: document.querySelector("#resetRenderingBtn"),
  connectBtn: document.querySelector("#connectBtn"),
  connectHrBtn: document.querySelector("#connectHrBtn"),
  demoModeBtn: document.querySelector("#demoModeBtn"),
  resizeRecordingWindowBtn: document.querySelector("#resizeRecordingWindowBtn"),
  theaterHudTogglesLabel: document.querySelector(".theater-hud-toggles-label"),
  theaterHideClockInput: document.querySelector("#theaterHideClockInput"),
  theaterHideMetersInput: document.querySelector("#theaterHideMetersInput"),
  theaterHideDockInput: document.querySelector("#theaterHideDockInput"),
  theaterHideClimbBannerInput: document.querySelector("#theaterHideClimbBannerInput"),
  theaterHideDemoChipInput: document.querySelector("#theaterHideDemoChipInput"),
  theaterHideControlsInput: document.querySelector("#theaterHideControlsInput"),
  theaterHideMinimapInput: document.querySelector("#theaterHideMinimapInput"),
  theaterHideRouteAheadInput: document.querySelector("#theaterHideRouteAheadInput"),
  demoBanner: document.querySelector("#demoBanner"),
  restingHeartRateInput: document.querySelector("#restingHeartRateInput"),
  maxHeartRateInput: document.querySelector("#maxHeartRateInput"),
  ftpInput: document.querySelector("#ftpInput"),
  powerZoneSummary: document.querySelector("#powerZoneSummary"),
  heartRateZoneSummary: document.querySelector("#heartRateZoneSummary"),
  zoneHelpButtons: document.querySelectorAll("[data-zone-help-trigger]"),
  startBtn: document.querySelector("#startBtn"),
  startBtnLabel: document.querySelector("#startBtnLabel"),
  resetBtn: document.querySelector("#resetBtn"),
  trainerDot: document.querySelector("#trainerDot"),
  hrDot: document.querySelector("#hrDot"),
  hrConnectionStat: document.querySelector("#hrConnectionStat"),
  recIndicator: document.querySelector("#recIndicator"),
  centerRiderBtn: document.querySelector("#centerRiderBtn"),
  progress: document.querySelector("#progress"),
  progressLabel: document.querySelector("#progressLabel"),
  ascentProgress: document.querySelector("#ascentProgress"),
  ascentProgressLabel: document.querySelector("#ascentProgressLabel"),
  profile: document.querySelector("#profile"),
  mapViewport: document.querySelector("#mapViewport"),
  mapActions: document.querySelector(".map-actions"),
  minimap: document.querySelector("#minimap"),
  fullscreenBtn: document.querySelector("#fullscreenBtn"),
  resetCameraControl: document.querySelector("#resetCameraControl"),
  resetCameraViewBtn: document.querySelector("#resetCameraViewBtn"),
  cameraViewMenuBtn: document.querySelector("#cameraViewMenuBtn"),
  cameraViewMenu: document.querySelector("#cameraViewMenu"),
  cameraViewButtons: Array.from(document.querySelectorAll("[data-camera-view-preset]")),
  mapOverviewControl: document.querySelector("#mapOverviewControl"),
  overviewToggleBtn: document.querySelector("#overviewToggleBtn"),
  overviewMenuBtn: document.querySelector("#overviewMenuBtn"),
  overviewModeMenu: document.querySelector("#overviewModeMenu"),
  overviewModeButtons: Array.from(document.querySelectorAll("[data-map-overview-mode]")),
  climbOverviewControl: document.querySelector("#climbOverviewControl"),
  climbOverviewToggleBtn: document.querySelector("#climbOverviewToggleBtn"),
  climbOverviewMenuBtn: document.querySelector("#climbOverviewMenuBtn"),
  climbOverviewModeMenu: document.querySelector("#climbOverviewModeMenu"),
  climbOverviewModeButtons: Array.from(document.querySelectorAll("[data-map-climb-mode]")),
  screenshotBtn: document.querySelector("#screenshotBtn"),
  screenshotButtonInput: document.querySelector("#screenshotButtonInput"),
  screenshotAspectSelect: document.querySelector("#screenshotAspectSelect"),
  screenshotWidthSelect: document.querySelector("#screenshotWidthSelect"),
  galleryTitleInput: document.querySelector("#galleryTitleInput"),
  galleryDescriptionInput: document.querySelector("#galleryDescriptionInput"),
  galleryMetadataOutput: document.querySelector("#galleryMetadataOutput"),
  copyGalleryMetadataBtn: document.querySelector("#copyGalleryMetadataBtn"),
  fullscreenOverlayBottom: document.querySelector("#fullscreenOverlayBottom"),
  hudPowerStat: document.querySelector("#hudPowerStat"),
  hudSpeedStat: document.querySelector("#hudSpeedStat"),
  hudHeartRateStat: document.querySelector("#hudHeartRateStat"),
  hudGradeStat: document.querySelector("#hudGradeStat"),
  hudRiddenStat: document.querySelector("#hudRiddenStat"),
  hudRemainingStat: document.querySelector("#hudRemainingStat"),
  hudAscentLeftStat: document.querySelector("#hudAscentLeftStat"),
  hudEtaStat: document.querySelector("#hudEtaStat"),
  hudCaloriesStat: document.querySelector("#hudCaloriesStat"),
  hudAltitudeStat: document.querySelector("#hudAltitudeStat"),
  hudAscentStat: document.querySelector("#hudAscentStat"),
  hudElapsedStat: document.querySelector("#hudElapsedStat"),
  hudTiles: document.querySelectorAll("#fullscreenHud [data-hud]"),
  hudOrderList: document.querySelector("#hudOrderList"),
  hudVisibleCountOutput: document.querySelector("#hudVisibleCountOutput"),
  hudLessBtn: document.querySelector("#hudLessBtn"),
  hudMoreBtn: document.querySelector("#hudMoreBtn"),
  hudSettingsBtn: document.querySelector("#hudSettingsBtn"),
  hudVisibleLessBtn: document.querySelector("#hudVisibleLessBtn"),
  hudVisibleMoreBtn: document.querySelector("#hudVisibleMoreBtn"),
  fullscreenHud: document.querySelector("#fullscreenHud"),
  profileSeriesButtons: document.querySelectorAll("[data-profile-series]"),
  // Fullscreen HUD: data dock, top-left clock chip, and top-center climb banner
  dockToggleBtn: document.querySelector("#dockToggleBtn"),
  fsProfileMount: document.querySelector("#fsProfileMount"),
  fsRoadRouteName: document.querySelector("#fsRoadRouteName"),
  fsRoadRouteProps: document.querySelector("#fsRoadRouteProps"),
  fsDistLabel: document.querySelector("#fsDistLabel"),
  fsDistFill: document.querySelector("#fsDistFill"),
  fsClimbLabel: document.querySelector("#fsClimbLabel"),
  fsClimbFill: document.querySelector("#fsClimbFill"),
  fullscreenClock: document.querySelector("#fullscreenClock"),
  fsClockLocal: document.querySelector("#fsClockLocal"),
  fsClockElapsed: document.querySelector("#fsClockElapsed"),
  fsClockDistance: document.querySelector("#fsClockDistance"),
  fsClockAscent: document.querySelector("#fsClockAscent"),
  fullscreenTrainingMeters: document.querySelector("#fullscreenTrainingMeters"),
  powerMeter: document.querySelector("#powerMeter"),
  heartRateMeter: document.querySelector("#heartRateMeter"),
  gradeMeter: document.querySelector("#gradeMeter"),
  cadenceMeter: document.querySelector("#cadenceMeter"),
  zonePowerValue: document.querySelector("#zonePowerValue"),
  zonePowerMeta: document.querySelector("#zonePowerMeta"),
  zonePowerFill: document.querySelector("#zonePowerFill"),
  zoneHeartRateValue: document.querySelector("#zoneHeartRateValue"),
  zoneHeartRateMeta: document.querySelector("#zoneHeartRateMeta"),
  zoneHeartRateFill: document.querySelector("#zoneHeartRateFill"),
  zoneGradeValue: document.querySelector("#zoneGradeValue"),
  zoneGradeMeta: document.querySelector("#zoneGradeMeta"),
  zoneGradeFill: document.querySelector("#zoneGradeFill"),
  zoneCadenceValue: document.querySelector("#zoneCadenceValue"),
  zoneCadenceMeta: document.querySelector("#zoneCadenceMeta"),
  zoneCadenceFill: document.querySelector("#zoneCadenceFill"),
  climbBanner: document.querySelector("#climbBanner"),
  climbBannerAhead: document.querySelector("#climbBannerAhead"),
  climbBannerOn: document.querySelector("#climbBannerOn"),
  segmentBanner: document.querySelector("#segmentBanner"),
  cbCategory: document.querySelector("#cbCategory"),
  cbAheadOrder: document.querySelector("#cbAheadOrder"),
  cbOnOrder: document.querySelector("#cbOnOrder"),
  cbInDist: document.querySelector("#cbInDist"),
  cbInUnit: document.querySelector("#cbInUnit"),
  cbMini: document.querySelector("#cbMini"),
  cbBaseAlt: document.querySelector("#cbBaseAlt"),
  cbPeakAltMini: document.querySelector("#cbPeakAltMini"),
  cbLen: document.querySelector("#cbLen"),
  cbGain: document.querySelector("#cbGain"),
  cbAvg: document.querySelector("#cbAvg"),
  cbMax: document.querySelector("#cbMax"),
  cbToTop: document.querySelector("#cbToTop"),
  cbToGo: document.querySelector("#cbToGo"),
  cbCurAlt: document.querySelector("#cbCurAlt"),
  cbPeakAlt: document.querySelector("#cbPeakAlt"),
  cbGradeLeft: document.querySelector("#cbGradeLeft"),
  cbDistFill: document.querySelector("#cbDistFill"),
  cbAscFill: document.querySelector("#cbAscFill"),
  sbStart: document.querySelector("#sbStart"),
  sbEnd: document.querySelector("#sbEnd"),
  sbLen: document.querySelector("#sbLen"),
  sbAsc: document.querySelector("#sbAsc"),
  sbDesc: document.querySelector("#sbDesc"),
  minimapInput: document.querySelector("#minimapInput"),
  mapLabelsInput: document.querySelector("#mapLabelsInput"),
  cameraDebugInput: document.querySelector("#cameraDebugInput"),
  cameraDebug: document.querySelector("#cameraDebug"),
  cameraDebugCollapseBtn: document.querySelector("#cameraDebugCollapseBtn"),
  cameraDebugBody: document.querySelector("#cameraDebugBody"),
  recDistanceStat: document.querySelector("#recDistanceStat"),
  recTimeStat: document.querySelector("#recTimeStat"),
  recPointsStat: document.querySelector("#recPointsStat"),
  recHeartRateStat: document.querySelector("#recHeartRateStat"),
  recCaloriesStat: document.querySelector("#recCaloriesStat"),
  downloadFitBtn: document.querySelector("#downloadFitBtn"),
  clearRideDataBtn: document.querySelector("#clearRideDataBtn"),
  streetImageryLayer: document.querySelector("#streetImageryLayer"),
  streetImageryChip: document.querySelector("#streetImageryChip"),
  streetImageryChipText: document.querySelector("#streetImageryChipText"),
  streetImageryChipContributeBtn: document.querySelector("#streetImageryChipContributeBtn"),
  streetImageryInput: document.querySelector("#streetImageryInput"),
  mapillaryTokenInput: document.querySelector("#mapillaryTokenInput"),
  mapillaryTokenSaveBtn: document.querySelector("#mapillaryTokenSaveBtn"),
  mapillaryTokenNote: document.querySelector("#mapillaryTokenNote"),
  mapillaryTokenHelpLink: document.querySelector("#mapillaryTokenHelpLink"),
  mapillaryUsernameInput: document.querySelector("#mapillaryUsernameInput"),
  streetImageryCoverage: document.querySelector("#streetImageryCoverage"),
  streetImageryCredit: document.querySelector("#streetImageryCredit"),
  imageryCacheStat: document.querySelector("#imageryCacheStat"),
  clearImageryCacheBtn: document.querySelector("#clearImageryCacheBtn"),
  contributeOpenBtn: document.querySelector("#contributeOpenBtn"),
  contributeDialog: document.querySelector("#contributeDialog"),
  contributeCloseBtn: document.querySelector("#contributeCloseBtn"),
  contributeDownloadGpxBtn: document.querySelector("#contributeDownloadGpxBtn"),
  contributeCheckCoverageBtn: document.querySelector("#contributeCheckCoverageBtn"),
  contributeCoverage: document.querySelector("#contributeCoverage"),
  contributeEnableBtn: document.querySelector("#contributeEnableBtn"),
  // Ride replay card + the theater-mode toolbar. Transport controls exist in
  // both places (card and toolbar) and are synced as groups.
  replayFile: document.querySelector("#replayFile"),
  replayStravaInput: document.querySelector("#replayStravaInput"),
  replayStravaFitBtn: document.querySelector("#replayStravaFitBtn"),
  replayStravaGpxBtn: document.querySelector("#replayStravaGpxBtn"),
  replayStravaHint: document.querySelector("#replayStravaHint"),
  replayEmpty: document.querySelector("#replayEmpty"),
  replayLoaded: document.querySelector("#replayLoaded"),
  replaySourceName: document.querySelector("#replaySourceName"),
  replayDurationStat: document.querySelector("#replayDurationStat"),
  replayDistanceStat: document.querySelector("#replayDistanceStat"),
  replayAvgSpeedStat: document.querySelector("#replayAvgSpeedStat"),
  replayChannelsStat: document.querySelector("#replayChannelsStat"),
  replayPreviewBtn: document.querySelector("#replayPreviewBtn"),
  ghostRiderInput: document.querySelector("#ghostRiderInput"),
  ghostChip: document.querySelector("#ghostChip"),
  ghostChipTime: document.querySelector("#ghostChipTime"),
  ghostChipDistance: document.querySelector("#ghostChipDistance"),
  ghostChipWord: document.querySelector("#ghostChipWord"),
  replayPlayButtons: Array.from(document.querySelectorAll("[data-replay-play]")),
  replayScrubbers: Array.from(document.querySelectorAll("[data-replay-scrub]")),
  replayTimeOutputs: Array.from(document.querySelectorAll("[data-replay-time]")),
  replaySpeedSelects: Array.from(document.querySelectorAll("[data-replay-speed]")),
  theaterToolbar: document.querySelector("#theaterToolbar"),
  theaterToolbarReplay: document.querySelector("#theaterToolbarReplay"),
  theaterExitBtn: document.querySelector("#theaterExitBtn"),
  replayRecordBtn: document.querySelector("#replayRecordBtn"),
  replayRecordStatus: document.querySelector("#replayRecordStatus"),
  replayCameraSelect: document.querySelector("#replayCameraSelect"),
  replayCopyCommandBtn: document.querySelector("#replayCopyCommandBtn"),
};

// One-line status readout under the progress bar; the app-wide way to tell
// the user what just happened (load errors, save notices, mode changes).
export function updateProgressLabel(text) {
  els.progressLabel.textContent = text;
}
